### PR TITLE
Matches with changes in Maliput: Lane::ToLanePosition.

### PR DESCRIPTION
**Pull request by francocipollone**
Related to https://github.com/maliput/maliput/issues/496

### Summary

Matches with https://github.com/maliput/maliput/pull/521

action-ros-ci-repos-override: https://gist.githubusercontent.com/francocipollone/bc261d73fcf1f6f3c9b41176a714c6b8/raw/10780d5a0698a69a7a9c869f5a031bdf98b6132c/maliput_dragway.repos

### CODE REVIEW

**Review by agalbachicar — CHANGES_REQUESTED** [review]
Please, add tests here.

**Review by agalbachicar — APPROVED** [review]
LGTM

**Comment by francocipollone** [comment]
@ros-pull-request-builder retest this please

**Comment by francocipollone** [comment]
@ros-pull-request-builder retest this please

**Comment by francocipollone** [comment]
@ros-pull-request-builder retest this please

**Comment by francocipollone** [comment]
@ros-pull-request-builder retest this please

**Comment by francocipollone** [comment]
@ros-pull-request-builder retest this please

**Comment by francocipollone** [comment]
@ros-pull-request-builder retest this please

**Comment by francocipollone** [comment]
@ros-pull-request-builder retest this please

**Comment by francocipollone** [comment]
@ros-pull-request-builder retest this please

**Pull request merged**
